
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BLFacadeInterface", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BLFacadeInterface {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "register", targetNamespace = "http://service/", className = "service.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://service/", className = "service.RegisterResponse")
    @Action(input = "http://service/BLFacadeInterface/registerRequest", output = "http://service/BLFacadeInterface/registerResponse")
    public void register(
        @WebParam(name = "arg0", targetNamespace = "")
        ConcreteFlight arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<service.ConcreteFlight>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getConcreteFlights", targetNamespace = "http://service/", className = "service.GetConcreteFlights")
    @ResponseWrapper(localName = "getConcreteFlightsResponse", targetNamespace = "http://service/", className = "service.GetConcreteFlightsResponse")
    @Action(input = "http://service/BLFacadeInterface/getConcreteFlightsRequest", output = "http://service/BLFacadeInterface/getConcreteFlightsResponse")
    public List<ConcreteFlight> getConcreteFlights(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllDepartingCities", targetNamespace = "http://service/", className = "service.GetAllDepartingCities")
    @ResponseWrapper(localName = "getAllDepartingCitiesResponse", targetNamespace = "http://service/", className = "service.GetAllDepartingCitiesResponse")
    @Action(input = "http://service/BLFacadeInterface/getAllDepartingCitiesRequest", output = "http://service/BLFacadeInterface/getAllDepartingCitiesResponse")
    public List<String> getAllDepartingCities();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getArrivalCitiesFrom", targetNamespace = "http://service/", className = "service.GetArrivalCitiesFrom")
    @ResponseWrapper(localName = "getArrivalCitiesFromResponse", targetNamespace = "http://service/", className = "service.GetArrivalCitiesFromResponse")
    @Action(input = "http://service/BLFacadeInterface/getArrivalCitiesFromRequest", output = "http://service/BLFacadeInterface/getArrivalCitiesFromResponse")
    public List<String> getArrivalCitiesFrom(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<service.ConcreteFlightContainer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getContainerConcreteFlights", targetNamespace = "http://service/", className = "service.GetContainerConcreteFlights")
    @ResponseWrapper(localName = "getContainerConcreteFlightsResponse", targetNamespace = "http://service/", className = "service.GetContainerConcreteFlightsResponse")
    @Action(input = "http://service/BLFacadeInterface/getContainerConcreteFlightsRequest", output = "http://service/BLFacadeInterface/getContainerConcreteFlightsResponse")
    public List<ConcreteFlightContainer> getContainerConcreteFlights(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2);

}
